version: '3.7'

services:

  # Config servers (typically a replica set)
  config-server-1:
    image: mongo:latest
    command: [ "bash", "-c",
      "chmod 400 /configdb/keyfile \
      && mongod --configsvr --config /configdb/mongod.conf --replSet configReplSet --port 27040"
    ]
    ports:
      - "27040:27040"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - ./local/mongodb/data/mongodb-config-server-1:/data/db
      - ./local/mongodb/config_three_instances/common:/configdb

  config-server-2:
    image: mongo:latest
    command: [ "bash", "-c",
      "chmod 400 /configdb/keyfile \
      && mongod --configsvr --config /configdb/mongod.conf --replSet configReplSet --port 27041"
    ]
    ports:
      - "27041:27041"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - ./local/mongodb/data/mongodb-config-server-2:/data/db
      - ./local/mongodb/config_three_instances/common:/configdb

  config-server-3:
    image: mongo:latest
    command: [ "bash", "-c",
      "chmod 400 /configdb/keyfile \
      && mongod --configsvr --config /configdb/mongod.conf --replSet configReplSet --port 27042"
    ]
    ports:
      - "27042:27042"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - ./local/mongodb/data/mongodb-config-server-3:/data/db
      - ./local/mongodb/config_three_instances/common:/configdb

  # TODO currently I have to make some manual actions on the primary node every time I start the stack without the data - this should be automated, but was taking too long to figure out all the issues
  mongodb-shard1-1:
    image: mongo:latest
    command: [ "bash", "-c",
      "chmod 400 /configdb/keyfile \
      && mongod --shardsvr --config /configdb/mongod.conf --replSet shard1 --port 27017"
    ]
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      IS_REPLICA_SET_SETUP: true
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./local/mongodb/data/mongodb-shard1-1:/data/db
      - ./local/mongodb/config_three_instances/common:/configdb

  mongodb-shard1-2:
    image: mongo:latest
    command: [ "bash", "-c",
      "chmod 400 /configdb/keyfile \
      && mongod --shardsvr --config /configdb/mongod.conf --replSet shard1 --port 27027"
    ]
    ports:
      - "27027:27027"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./local/mongodb/data/mongodb-shard1-2:/data/db
      - ./local/mongodb/config_three_instances/common:/configdb

  mongodb-shard1-3:
    image: mongo:latest
    command: [ "bash", "-c",
      "chmod 400 /configdb/keyfile \
      && mongod --shardsvr --config /configdb/mongod.conf --replSet shard1 --port 27037"
    ]
    ports:
      - "27037:27037"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./local/mongodb/data/mongodb-shard1-3:/data/db
      - ./local/mongodb/config_three_instances/common:/configdb

  mongodb-shard2-1:
    image: mongo:latest
    command: [ "bash", "-c",
      "chmod 400 /configdb/keyfile \
      && mongod --shardsvr --config /configdb/mongod.conf --replSet shard2 --port 27018"
    ]
    ports:
      - "27018:27018"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      IS_REPLICA_SET_SETUP: true
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./local/mongodb/data/mongodb-shard2-1:/data/db
      - ./local/mongodb/config_three_instances/common:/configdb

  mongodb-shard2-2:
    image: mongo:latest
    command: [ "bash", "-c",
      "chmod 400 /configdb/keyfile \
      && mongod --shardsvr --config /configdb/mongod.conf --replSet shard2 --port 27028"
    ]
    ports:
      - "27028:27028"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./local/mongodb/data/mongodb-shard2-2:/data/db
      - ./local/mongodb/config_three_instances/common:/configdb

  mongodb-shard2-3:
    image: mongo:latest
    command: [ "bash", "-c",
      "chmod 400 /configdb/keyfile \
      && mongod --shardsvr --config /configdb/mongod.conf --replSet shard2 --port 27038"
    ]
    ports:
      - "27038:27038"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./local/mongodb/data/mongodb-shard2-3:/data/db
      - ./local/mongodb/config_three_instances/common:/configdb

  # Mongos Router
  mongos:
    image: mongo:latest
    command: >
      mongos --config /configdb/mongod.conf --port 27050 --configdb configReplSet/config-server-1:27040,config-server-2:27041,config-server-3:27042
    ports:
      - "27050:27050"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    depends_on:
      - config-server-1
      - config-server-2
      - config-server-3
    restart: always
    volumes:
      - ./local/mongodb/data/router:/data/db
      - ./local/mongodb/config_three_instances/common:/configdb

